export function getMoneyFormat(value: number, code: string = ""): string {
	const valueFormatted = (Math.round(value * 100) / 100).toFixed(2);
	if (code === "") return valueFormatted;

	const symbol = getCurrencySymbol(code);
	if (symbol === "") return valueFormatted;

	return `${symbol} ${valueFormatted}`;
}

export function getCurrencySymbol(code: string): string {
	switch (code) {
		case "AED":
			return "AED";
		case "AFN":
			return "؋";
		case "ALL":
			return "L";
		case "AMD":
			return "֏";
		case "ANG":
			return "ƒ";
		case "AOA":
			return "Kz";
		case "ARS":
			return "$";
		case "AUD":
			return "$";
		case "AWG":
			return "ƒ";
		case "AZN":
			return "₼";
		case "BAM":
			return "KM";
		case "BBD":
			return "$";
		case "BDT":
			return "৳";
		case "BGN":
			return "лв";
		case "BHD":
			return ".د.ب";
		case "BIF":
			return "FBu";
		case "BMD":
			return "$";
		case "BND":
			return "$";
		case "BOB":
			return "$b";
		case "BOV":
			return "BOV";
		case "BRL":
			return "R$";
		case "BSD":
			return "$";
		case "BTC":
			return "₿";
		case "BTN":
			return "Nu.";
		case "BWP":
			return "P";
		case "BYN":
			return "Br";
		case "BYR":
			return "Br";
		case "BZD":
			return "BZ$";
		case "CAD":
			return "$";
		case "CDF":
			return "FC";
		case "CHE":
			return "CHE";
		case "CHF":
			return "CHF";
		case "CHW":
			return "CHW";
		case "CLF":
			return "CLF";
		case "CLP":
			return "$";
		case "CNH":
			return "¥";
		case "CNY":
			return "¥";
		case "COP":
			return "$";
		case "COU":
			return "COU";
		case "CRC":
			return "₡";
		case "CUC":
			return "$";
		case "CUP":
			return "₱";
		case "CVE":
			return "$";
		case "CZK":
			return "Kč";
		case "DJF":
			return "Fdj";
		case "DKK":
			return "kr";
		case "DOP":
			return "RD$";
		case "DZD":
			return "دج";
		case "EEK":
			return "kr";
		case "EGP":
			return "£";
		case "ERN":
			return "Nfk";
		case "ETB":
			return "Br";
		case "ETH":
			return "Ξ";
		case "EUR":
			return "€";
		case "FJD":
			return "$";
		case "FKP":
			return "£";
		case "GBP":
			return "£";
		case "GEL":
			return "₾";
		case "GGP":
			return "£";
		case "GHC":
			return "₵";
		case "GHS":
			return "GH₵";
		case "GIP":
			return "£";
		case "GMD":
			return "D";
		case "GNF":
			return "FG";
		case "GTQ":
			return "Q";
		case "GYD":
			return "$";
		case "HKD":
			return "$";
		case "HNL":
			return "L";
		case "HRK":
			return "kn";
		case "HTG":
			return "G";
		case "HUF":
			return "Ft";
		case "IDR":
			return "Rp";
		case "ILS":
			return "₪";
		case "IMP":
			return "£";
		case "INR":
			return "₹";
		case "IQD":
			return "ع.د";
		case "IRR":
			return "﷼";
		case "ISK":
			return "kr";
		case "JEP":
			return "£";
		case "JMD":
			return "J$";
		case "JOD":
			return "JD";
		case "JPY":
			return "¥";
		case "KES":
			return "KSh";
		case "KGS":
			return "лв";
		case "KHR":
			return "៛";
		case "KMF":
			return "CF";
		case "KPW":
			return "₩";
		case "KRW":
			return "₩";
		case "KWD":
			return "KD";
		case "KYD":
			return "$";
		case "KZT":
			return "₸";
		case "LAK":
			return "₭";
		case "LBP":
			return "£";
		case "LKR":
			return "₨";
		case "LRD":
			return "$";
		case "LSL":
			return "M";
		case "LTC":
			return "Ł";
		case "LTL":
			return "Lt";
		case "LVL":
			return "Ls";
		case "LYD":
			return "LD";
		case "MAD":
			return "MAD";
		case "MDL":
			return "lei";
		case "MGA":
			return "Ar";
		case "MKD":
			return "ден";
		case "MMK":
			return "K";
		case "MNT":
			return "₮";
		case "MOP":
			return "MOP$";
		case "MRO":
			return "UM";
		case "MRU":
			return "UM";
		case "MUR":
			return "₨";
		case "MVR":
			return "Rf";
		case "MWK":
			return "MK";
		case "MXN":
			return "$";
		case "MXV":
			return "MXV";
		case "MYR":
			return "RM";
		case "MZN":
			return "MT";
		case "NAD":
			return "$";
		case "NGN":
			return "₦";
		case "NIO":
			return "C$";
		case "NOK":
			return "kr";
		case "NPR":
			return "₨";
		case "NZD":
			return "$";
		case "OMR":
			return "﷼";
		case "PAB":
			return "B/.";
		case "PEN":
			return "S/.";
		case "PGK":
			return "K";
		case "PHP":
			return "₱";
		case "PKR":
			return "₨";
		case "PLN":
			return "zł";
		case "PYG":
			return "Gs";
		case "QAR":
			return "﷼";
		case "RMB":
			return "￥";
		case "RON":
			return "lei";
		case "RSD":
			return "Дин.";
		case "RUB":
			return "₽";
		case "RWF":
			return "R₣";
		case "SAR":
			return "﷼";
		case "SBD":
			return "$";
		case "SCR":
			return "₨";
		case "SDG":
			return "ج.س.";
		case "SEK":
			return "kr";
		case "SGD":
			return "S$";
		case "SHP":
			return "£";
		case "SLL":
			return "Le";
		case "SOS":
			return "S";
		case "SRD":
			return "$";
		case "SSP":
			return "£";
		case "STD":
			return "Db";
		case "STN":
			return "Db";
		case "SVC":
			return "$";
		case "SYP":
			return "£";
		case "SZL":
			return "E";
		case "THB":
			return "฿";
		case "TJS":
			return "SM";
		case "TMT":
			return "T";
		case "TND":
			return "د.ت";
		case "TOP":
			return "T$";
		case "TRL":
			return "₤";
		case "TRY":
			return "₺";
		case "TTD":
			return "TT$";
		case "TVD":
			return "$";
		case "TWD":
			return "NT$";
		case "TZS":
			return "TSh";
		case "UAH":
			return "₴";
		case "UGX":
			return "USh";
		case "USD":
			return "$";
		case "UYI":
			return "UYI";
		case "UYU":
			return "$U";
		case "UYW":
			return "UYW";
		case "UZS":
			return "лв";
		case "VEF":
			return "Bs";
		case "VES":
			return "Bs.S";
		case "VND":
			return "₫";
		case "VUV":
			return "VT";
		case "WST":
			return "WS$";
		case "XAF":
			return "FCFA";
		case "XBT":
			return "Ƀ";
		case "XCD":
			return "$";
		case "XOF":
			return "CFA";
		case "XPF":
			return "₣";
		case "XSU":
			return "Sucre";
		case "XUA":
			return "XUA";
		case "YER":
			return "﷼";
		case "ZAR":
			return "R";
		case "ZMW":
			return "ZK";
		case "ZWD":
			return "Z$";
		case "ZWL":
			return "$";
		default:
			return "";
	}
}
